bridges = []
[[instances]]
name = "H_Wiki"
id = "__H_Wiki"
dna_hash = "QmcNYhU15GLbF6ibU73zHn6WfVwUgnBXXd4bZLGPUs55xC"
uri = "file:dist/holo_wiki.dna.json" 
[[UIs]]
name = "H_Wiki"
id = "H_Wiki"
uri = "dir:./build" 
[[UIs.instance_references]]
ui_handle = "__H_Wiki"
instance_id = "__H_Wiki"
[network]
type='sim2h'
sim2h_url= 'ws://localhost:9000' 